name 'chef-nginx'
maintainer 'El Sai'
maintainer_email 'N/A'
license 'All Rights Reserved'
description 'Installs/Configures chef-nginx'
long_description 'Installs/Configures chef-nginx'
version '0.1.0'
chef_version '>= 13.0'
